{\rtf1\ansi\ansicpg1252\cocoartf1561\cocoasubrtf600
{\fonttbl\f0\fnil\fcharset0 AndaleMono;}
{\colortbl;\red255\green255\blue255;\red47\green255\blue18;\red0\green0\blue0;\red159\green160\blue28;
\red180\green36\blue25;\red19\green102\blue7;}
{\*\expandedcolortbl;;\cssrgb\c15686\c99608\c7843;\csgray\c0\c90000;\cssrgb\c68469\c68013\c14209;
\cssrgb\c76410\c21699\c12524;\csgenericrgb\c7381\c40000\c2839\c94000;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs36 \cf2 \cb3 \CocoaLigature0 Last login: Sat Oct 20 22:10:09 on ttys001\
-bash: export: `5.3.0': not a valid identifier\
~ $ls\
Applications			Qt\
CLionProjects			Qt5.8.0\
Desktop				README.md\
Documents			eval "$(ssh-agent -s)"\
Downloads			eval "$(ssh-agent -s)".pub\
Library				flask-by-example\
Movies				hat\
Music				myproject\
Pictures			newproject\
Public				project\
PycharmProjects\
~ $python3 /Users/ellis/Desktop/flash_examples/basic.py \
  File "/Users/ellis/Desktop/flash_examples/basic.py", line 9\
    return render_template('basic.html', name=name)\
                                                  ^\
IndentationError: unindent does not match any outer indentation level\
~ $python3 /Users/ellis/Desktop/flash_examples/basic.py \
Traceback (most recent call last):\
  File "/Users/ellis/Desktop/flash_examples/basic.py", line 1, in <module>\
    from flask import Flask, render_template\
ModuleNotFoundError: No module named 'flask'\
~ $pip3 install flask\
Collecting flask\
  Using cached https://files.pythonhosted.org/packages/7f/e7/08578774ed4536d3242b14dacb4696386634607af824ea997202cd0edb4b/Flask-1.0.2-py2.py3-none-any.whl\
Collecting click>=5.1 (from flask)\
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl\
Collecting Jinja2>=2.10 (from flask)\
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl\
Collecting itsdangerous>=0.24 (from flask)\
  Using cached https://files.pythonhosted.org/packages/c9/c3/8dadb353944803796515ce68ad3944e6e7acc934f5036c40829cb96e64a1/ItsDangerous-1.0.0-py2.py3-none-any.whl\
Collecting Werkzeug>=0.14 (from flask)\
  Using cached https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl\
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10->flask)\
Installing collected packages: click, MarkupSafe, Jinja2, itsdangerous, Werkzeug, flask\
Successfully installed Jinja2-2.10 MarkupSafe-1.0 Werkzeug-0.14.1 click-7.0 flask-1.0.2 itsdangerous-1.0.0\
\cf4 You are using pip version 10.0.1, however version 18.1 is available.\cf2 \
\cf4 You should consider upgrading via the 'pip install --upgrade pip' command.\cf2 \
~ $python3 /Users/ellis/Desktop/flash_examples/basic.py \
 * Serving Flask app "basic" (lazy loading)\
 * Environment: production\
\cf5    WARNING: Do not use the development server in a production environment.\cf2 \
\cf6    Use a production WSGI server instead.\cf2 \
 * Debug mode: on\
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\
 * Restarting with stat\
 * Debugger is active!\
 * Debugger PIN: 146-458-470\
127.0.0.1 - - [20/Oct/2018 22:27:18] "GET / HTTP/1.1" 200 -\
127.0.0.1 - - [20/Oct/2018 22:27:18] "GET /static/dog.jpg HTTP/1.1" 200 -\
127.0.0.1 - - [20/Oct/2018 22:27:18] "GET /favicon.ico HTTP/1.1" 404 -\
 * Detected change in '/Users/ellis/Desktop/flash_examples/basic.py', reloading\
 * Restarting with stat\
 * Debugger is active!\
 * Debugger PIN: 146-458-470\
 * Detected change in '/Users/ellis/Desktop/flash_examples/basic.py', reloading\
 * Restarting with stat\
 * Debugger is active!\
 * Debugger PIN: 146-458-470\
 * Detected change in '/Users/ellis/Desktop/flash_examples/basic.py', reloading\
 * Restarting with stat\
 * Debugger is active!\
 * Debugger PIN: 146-458-470\
127.0.0.1 - - [20/Oct/2018 23:04:12] "GET / HTTP/1.1" 200 -\
127.0.0.1 - - [20/Oct/2018 23:04:12] "GET /favicon.ico HTTP/1.1" 404 -\
 * Detected change in '/Users/ellis/Desktop/flash_examples/basic.py', reloading\
 * Restarting with stat\
 * Debugger is active!\
 * Debugger PIN: 146-458-470\
127.0.0.1 - - [20/Oct/2018 23:12:12] "GET / HTTP/1.1" 200 -\
 * Detected change in '/Users/ellis/Desktop/flash_examples/basic.py', reloading\
 * Restarting with stat\
 * Debugger is active!\
 * Debugger PIN: 146-458-470\
127.0.0.1 - - [20/Oct/2018 23:14:15] "GET / HTTP/1.1" 500 -\
Traceback (most recent call last):\
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2309, in __call__\
    return self.wsgi_app(environ, start_response)\
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2295, in wsgi_app\
    response = self.handle_exception(e)\
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1741, in handle_exception\
    reraise(exc_type, exc_value, tb)\
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise\
    raise value\
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app\
    response = self.full_dispatch_request()\
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request\
    rv = self.handle_user_exception(e)\
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception\
    reraise(exc_type, exc_value, tb)\
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise\
    raise value\
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request\
    rv = self.dispatch_request()\
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request\
    return self.view_functions[rule.endpoint](**req.view_args)\
  File "/Users/ellis/Desktop/flash_examples/basic.py", line 9, in index\
    return render_template('basic.html', mylist=mylist)\
NameError: name 'mylist' is not defined\
127.0.0.1 - - [20/Oct/2018 23:14:15] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -\
127.0.0.1 - - [20/Oct/2018 23:14:15] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -\
127.0.0.1 - - [20/Oct/2018 23:14:15] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -\
127.0.0.1 - - [20/Oct/2018 23:14:15] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -\
127.0.0.1 - - [20/Oct/2018 23:14:15] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -\
127.0.0.1 - - [20/Oct/2018 23:14:15] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -\
 * Detected change in '/Users/ellis/Desktop/flash_examples/basic.py', reloading\
 * Restarting with stat\
 * Debugger is active!\
 * Debugger PIN: 146-458-470\
127.0.0.1 - - [20/Oct/2018 23:14:48] "GET / HTTP/1.1" 200 -\
 * Detected change in '/Users/ellis/Desktop/flash_examples/basic.py', reloading\
 * Restarting with stat\
  File "/Users/ellis/Desktop/flash_examples/basic.py", line 11\
    deft pup_name(name)\
       ^\
SyntaxError: invalid syntax\
~ $python3 python3 /Users/ellis/Desktop/flash_examples/basic.py \
/Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'python3': [Errno 2] No such file or directory\
~ $python3 /Users/ellis/Desktop/flash_examples/templates/basic.html \
  File "/Users/ellis/Desktop/flash_examples/templates/basic.html", line 1\
    <!DOCTYPE html>\
    ^\
SyntaxError: invalid syntax\
~ $\
}